"""
AI Compare Engine - rigorous side-by-side technical comparison of up to 4 components,
generated by the LLM, grounded in the products' own researched data.
"""
import json
import logging
from typing import List, Dict

from integrations.llm_client import generate_json

logger = logging.getLogger(__name__)

COMPARE_SYSTEM_MESSAGE = (
    "You are a senior electrical engineer performing a rigorous side-by-side technical comparison "
    "of components for EV charging and solar industrial projects. Base your analysis on the provided "
    "product data. Always respond with strict, valid, parseable JSON only - no markdown, no commentary."
)


def _build_compare_prompt(products: List[dict], category: str) -> str:
    products_json = json.dumps(products, indent=2, default=str)[:9000]
    return f"""Compare the following {len(products)} electrical/EV/solar components (category: {category or 'general'}):

{products_json}

Provide a rigorous engineering comparison for a procurement/engineering team. Return ONLY valid JSON
with EXACTLY this structure:
{{
  "comparison_summary": "2-3 sentence overview of how these products compare",
  "spec_comparison": [
    {{"spec_name": "string", "values": {{"<product name>": "value"}}}}
  ],
  "feature_comparison": [
    {{"feature": "string", "notes": "string"}}
  ],
  "winner_overall": "<exact product name>",
  "winner_reason": "string",
  "best_value": "<exact product name>",
  "best_value_reason": "string",
  "best_industrial": "<exact product name>",
  "best_industrial_reason": "string",
  "per_product_advantages": {{"<exact product name>": ["string"]}},
  "per_product_disadvantages": {{"<exact product name>": ["string"]}}
}}"""


async def compare_products(products: List[dict], category: str = '') -> Dict:
    prompt = _build_compare_prompt(products, category)
    parsed = await generate_json(COMPARE_SYSTEM_MESSAGE, prompt)
    if not parsed:
        raise RuntimeError('AI comparison failed to generate a valid result. Please try again.')
    return parsed
